export const RECEIVE_USER = "RECEIVE_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CHANGE_LOADING_STATUS = "CHANGE_LOADING_STATUS";
export const RECEIVE_ORDER = "RECEIVE_ORDER";
export const RECEIVE_ORDERS_LIST = "RECEIVE_ORDERS_LIST";
